kanshanos:
  datasentry:
    enabled: true
    sampling-rate: 1
    exclude-path-patterns:
      - /user
    request-rate-window-interval-seconds: 10
    sensitive-detection-hit-window-interval-seconds: 20
